"""Create export table

Revision ID: 4371106dcddc
Revises: 1579557e0069
Create Date: 2025-06-28 02:21:16.784590

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4371106dcddc"
down_revision: Union[str, Sequence[str], None] = "1579557e0069"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pylint: disable=no-member
    op.create_table(
        "export_pipelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # pylint: disable=no-member
    op.create_index(
        op.f("ix_export_pipelines_tenant_id"),
        "export_pipelines",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pylint: disable=no-member
    op.drop_index(
        op.f("ix_export_pipelines_tenant_id"),
        table_name="export_pipelines",
    )
    # pylint: disable=no-member
    op.drop_table("export_pipelines")
    # ### end Alembic commands ###
